//to be read, reading, read

export const booksData = [
  {
    id: "2166584",
    status: "to be read",
    title:
      "WordPress for Web Developers: An Introduction for Web Professionals",
    author: "Stephanie Leary (auth.)",
    author_firstname: null,
    author_lastname: "",
    author_middlename: "",
    categories: "Computers\\\\Web-design",
    volume: "",
    year: "2013",
    edition: "",
    language: "en",
    extension: "pdf",
    pages: "356",
    filesize: "6016788",
    md5: "5e9210c7793553e45a1a3f306c42f642",
    series: "",
    periodical: "",
    file_extension: "pdf",
    url: "http://bookzz.org/dl/2166584/e253e6",
    convertTo: {
      epub: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F1012000%2F5e9210c7793553e45a1a3f306c42f642&input_format=pdf&output_format=EPUB&download=1",
      fb2: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F1012000%2F5e9210c7793553e45a1a3f306c42f642&input_format=pdf&output_format=FB2&download=1",
      mobi: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F1012000%2F5e9210c7793553e45a1a3f306c42f642&input_format=pdf&output_format=MOBI&download=1",
      txt: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F1012000%2F5e9210c7793553e45a1a3f306c42f642&input_format=pdf&output_format=TXT&download=1",
      rtf: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F1012000%2F5e9210c7793553e45a1a3f306c42f642&input_format=pdf&output_format=RTF&download=1",
    },
    description: "",
    cover:
      "http://link.springer.com/static-content/covers/books/642/9781430258674.jpg",
  },
  {
    id: "643521",
    status: "to be read",
    title: "MODx Web Development",
    author: "Antano Solar John, Antano Solar John",
    author_firstname: null,
    author_lastname: "",
    author_middlename: "",
    categories: "Computer Science/Web/Server Side Scripting/PHP",
    volume: "",
    year: "2009",
    edition: "",
    language: "en",
    extension: "pdf",
    pages: "276",
    filesize: "6044490",
    md5: "DFB074A1D600635E8B92C4BD948F0C3A",
    series: "",
    periodical: "",
    file_extension: "pdf",
    url: "http://bookzz.org/dl/643521/621c7c",
    convertTo: {
      epub: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F215000%2Fdfb074a1d600635e8b92c4bd948f0c3a&input_format=pdf&output_format=EPUB&download=1",
      fb2: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F215000%2Fdfb074a1d600635e8b92c4bd948f0c3a&input_format=pdf&output_format=FB2&download=1",
      mobi: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F215000%2Fdfb074a1d600635e8b92c4bd948f0c3a&input_format=pdf&output_format=MOBI&download=1",
      txt: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F215000%2Fdfb074a1d600635e8b92c4bd948f0c3a&input_format=pdf&output_format=TXT&download=1",
      rtf: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F215000%2Fdfb074a1d600635e8b92c4bd948f0c3a&input_format=pdf&output_format=RTF&download=1",
    },
    description:
      "Like someone else said, you can learn MODx by finding resources on the internet. I started reading this book to get introduced to the system, and it was OK for that, but I found I didn't really use it or need it when I actually started making my MODx site. It's a good overview/introduction that may help you understand what MODx is and how it functions, but not totally needed if you just want to jump right in and make a site with MODx. Also, since the release of MODx 1.0/1.0.1, the terminology used in this book is no longer correct, so it may actually confuse you (Resources are now Elements, Documents are now Resources, etc.) And I found some of the writing to be awkward.",
    cover:
      "http://libgen.org/covers/215000/dfb074a1d600635e8b92c4bd948f0c3a-d.jpg",
  },
  {
    id: "682493",
    status: "to be read",
    title: "Grok 1.0 Web Development",
    author: "Carlos de la Guardia",
    author_firstname: null,
    author_lastname: "",
    author_middlename: "",
    categories: "Computing -Web",
    volume: "",
    year: "2010",
    edition: "",
    language: "en",
    extension: "pdf",
    pages: "307",
    filesize: "2834507",
    md5: "3D19832E2EABC88C4079244FC8D56DC1",
    series: "",
    periodical: "",
    file_extension: "pdf",
    url: "http://bookzz.org/dl/682493/3346a7",
    convertTo: {
      epub: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F254000%2F3d19832e2eabc88c4079244fc8d56dc1&input_format=pdf&output_format=EPUB&download=1",
      fb2: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F254000%2F3d19832e2eabc88c4079244fc8d56dc1&input_format=pdf&output_format=FB2&download=1",
      mobi: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F254000%2F3d19832e2eabc88c4079244fc8d56dc1&input_format=pdf&output_format=MOBI&download=1",
      txt: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F254000%2F3d19832e2eabc88c4079244fc8d56dc1&input_format=pdf&output_format=TXT&download=1",
      rtf: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F254000%2F3d19832e2eabc88c4079244fc8d56dc1&input_format=pdf&output_format=RTF&download=1",
    },
    description:
      'Grok 1.0 Web Development is a great introduction to what I think is a very powerful web technology stack: the Zope Toolkit.  Grok provides a way for newcomers and those familiar with other Python web stacks to get started with ZTK, which can often seem insular, cryptic, and inaccessible.  When a user is ready to "move up", they can start leveraging the power that underlies Grok.  This book is a good introduction to that stack.  \r\rGrok 1.0 Web Development takes what as I think of as a customary approach to framework introductions, instructing the user on the basic features of the framework by building an application (in this case a to do list manager) and adding features and refining the code as it goes. This works well for Grok -- the amount of boilerplate code is kept to a minimum, by design, so the text can focus on first implementing the feature, then delving deeper to discuss the "best practice" around that tool if needed. For example, Chapter 6 covers ZODB Catalogs (index). It starts by defining the search view and user interface so that the reader has a functioning search tool to work with, then takes a diversion to discuss how one best structures their application to support search. These detailed drill downs are one of the most valuable parts of Grok 1.0 Web Development: they help the reader expand their understand beyond just implementing a feature, to implementing in a way that will be flexible and easy to support in the future. The [somewhat brief] advice on when to use the ZODB versus a relational database is another example of practical advice that I appreciated in the book.\r\rGrok 1.0 Web Development is not perfect. In particular I wish the chapter on testing were earlier (the author\'s admonition that it "should not be treated as an afterthought" doesn\'t seem to jibe with its placement among the advanced topics towards the end of the book. I suppose I\'m also a little sensitive to slogging on Zope 3 and it\'s "lack" of agility. I can probably be described as a Zope 3 / Zope component architecture apologist, but it seems the type of agility described is a rather narrow, specific definition. The sprints I did on Zope 3 at PyCon several years contributed more to my understanding and appreciation of test driven development and agile planning than just about anything. Yes, Grok gets it done without the ZCML; I think it\'s an exercise for the reader as to whether that\'s better or worse for your application.\r\rI think that the Zope derived frameworks such as Grok and repoze.bfg are some of the most interesting in development today. Grok 1.0 Web Development does a great job of introducing Grok to developers who are new to web programming, or who already have some familiarity with another framework. I recommend it to anyone interested in building extensible web applications with a minimum of boilerplate.',
    cover:
      "http://libgen.org/covers/254000/3d19832e2eabc88c4079244fc8d56dc1-d.jpg",
  },
  {
    id: "682507",
    status: "to be read",
    title: "Professional JavaScript for Web Developers",
    author: "Nicholas C. Zakas",
    author_firstname: null,
    author_lastname: "",
    author_middlename: "",
    categories: "Computing -Web",
    volume: "",
    year: "2009",
    edition: "2",
    language: "en",
    extension: "pdf",
    pages: "841",
    filesize: "5510920",
    md5: "B07ADFCAF9641B17FE76115BF174F44C",
    series: "Wrox Programmer to Programmer",
    periodical: "",
    file_extension: "pdf",
    url: "http://bookzz.org/dl/682507/a9cd0c",
    convertTo: {
      epub: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F254000%2Fb07adfcaf9641b17fe76115bf174f44c&input_format=pdf&output_format=EPUB&download=1",
      fb2: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F254000%2Fb07adfcaf9641b17fe76115bf174f44c&input_format=pdf&output_format=FB2&download=1",
      mobi: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F254000%2Fb07adfcaf9641b17fe76115bf174f44c&input_format=pdf&output_format=MOBI&download=1",
      txt: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F254000%2Fb07adfcaf9641b17fe76115bf174f44c&input_format=pdf&output_format=TXT&download=1",
      rtf: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F254000%2Fb07adfcaf9641b17fe76115bf174f44c&input_format=pdf&output_format=RTF&download=1",
    },
    description:
      "Probably the most complete and updated book that you may find about Javascript.The author made a great job writting about some of the most important topics on javascript development and highlighting the difference among browsers.Most of the topics are already covered in other javascript books I have read before, but not in the way Nicholas does, he usually goes deeper on every topic.If you have some knowledge on javascript and want to reach another level, this is the book for you. If you consider yourself a guru, you may enjoy it as well, but definitely, not for newbies.",
    cover:
      "http://libgen.org/covers/254000/b07adfcaf9641b17fe76115bf174f44c-d.jpg",
  },
  {
    id: "740977",
    status: "to be read",
    title:
      "Art of Java Web Development: Struts, Tapestry, Commons, Velocity, JUnit, Axis, Cocoon, InternetBeans, WebWork",
    author: "Neal Ford",
    author_firstname: null,
    author_lastname: "",
    author_middlename: "",
    categories: "computers, computers/web",
    volume: "",
    year: "2003",
    edition: "",
    language: "en",
    extension: "pdf",
    pages: "624",
    filesize: "6014775",
    md5: "2D822F49188D9EDAA78F2085F8E2737F",
    series: "",
    periodical: "",
    file_extension: "pdf",
    url: "http://bookzz.org/dl/740977/339164",
    convertTo: {
      epub: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F314000%2F2d822f49188d9edaa78f2085f8e2737f&input_format=pdf&output_format=EPUB&download=1",
      fb2: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F314000%2F2d822f49188d9edaa78f2085f8e2737f&input_format=pdf&output_format=FB2&download=1",
      mobi: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F314000%2F2d822f49188d9edaa78f2085f8e2737f&input_format=pdf&output_format=MOBI&download=1",
      txt: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F314000%2F2d822f49188d9edaa78f2085f8e2737f&input_format=pdf&output_format=TXT&download=1",
      rtf: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F314000%2F2d822f49188d9edaa78f2085f8e2737f&input_format=pdf&output_format=RTF&download=1",
    },
    description:
      "A guide to the topics required for state of the art Web development, this book covers wide-ranging topics, including a variety of web development frameworks and best practices. Beginning with coverage of the history of the architecture of Web applications, highlighting the uses of the standard web API to create applications with increasingly sophisticated architectures, developers are led through a discussion on the development of industry accepted best practices for architecture. Described is the history and evolution towards this architecture and the reasons that it is superior to previous efforts. Also provided is an overview of the most popular Web application frameworks, covering their architecture and use. Numerous frameworks exist, but trying to evaluate them is difficult because their documentation stresses their advantages but hides their deficiencies. Here, the same application is built in six different frameworks, providing a way to perform an informed comparison. Also provided is an evaluation of the pros and cons of each framework to assist in making a decision or evaluating a framework on your own. Finally, best practices are covered, including sophisticated user interface techniques, intelligent caching and resource management, performance tuning, debugging, testing, and Web services.",
    cover:
      "http://libgen.org/covers/314000/2d822f49188d9edaa78f2085f8e2737f-d.jpg",
  },
  {
    id: "826704",
    status: "to be read",
    title: "Agile.Web.Development.with.Rails.4th.Edition",
    author: "the pragmatic programmers",
    author_firstname: null,
    author_lastname: "",
    author_middlename: "",
    categories: "web programming",
    volume: "",
    year: "0",
    edition: null,
    language: "",
    extension: "pdf",
    pages: "0",
    filesize: "8677488",
    md5: "1e1082ced7f59e0d92c047d465a37578",
    series: "",
    periodical: null,
    file_extension: "pdf",
    url: "http://bookzz.org/dl/826704/0477c2",
    convertTo: null,
    description: "",
    cover: null,
  },
  {
    id: "879439",
    status: "to be read",
    title: "Beginning CSS Web Development: From Novice to Professional",
    author: "Simon Collison",
    author_firstname: null,
    author_lastname: "",
    author_middlename: "",
    categories: "Компьютеры//Web-дизайн",
    volume: "",
    year: "2006",
    edition: "",
    language: "en",
    extension: "pdf",
    pages: "448",
    filesize: "19215261",
    md5: "ee845efa4da1004f1177ae9b498eca22",
    series: "",
    periodical: "",
    file_extension: "pdf",
    url: "http://bookzz.org/dl/879439/c82b5c",
    convertTo: null,
    description: "",
    cover:
      "http://libgen.org/covers/454000/ee845efa4da1004f1177ae9b498eca22-d.jpg",
  },
  {
    id: "1159094",
    status: "to be read",
    title: "Beginning PHP 6, Apache, MySQL 6 Web Development",
    author: "Timothy Boronczyk",
    author_firstname: null,
    author_lastname: "",
    author_middlename: "",
    categories: "КНИГИ  WEB-СОЗИДАНИЕ",
    volume: "",
    year: "2009",
    edition: "",
    language: "en",
    extension: "pdf",
    pages: "0",
    filesize: "12490028",
    md5: "2D53E184F32B5CAD6FE01E581DCDAE2C",
    series: "",
    periodical: "",
    file_extension: "pdf",
    url: "http://bookzz.org/dl/1159094/8c2032",
    convertTo: null,
    description: "",
    cover:
      "http://libgen.org/covers/721000/2d53e184f32b5cad6fe01e581dcdae2c-g.jpg",
  },
  {
    id: "2054864",
    status: "to be read",
    title:
      "Web development solutions : Ajax, APIs, libraries, and hosted services made easy",
    author: "Christian Heilmann; Mark Norman Francis",
    author_firstname: null,
    author_lastname: "",
    author_middlename: "",
    categories: "Computers\\\\Web-design",
    volume: "",
    year: "0",
    edition: "",
    language: "en",
    extension: "pdf",
    pages: "268",
    filesize: "6194470",
    md5: "b544a6be89e10bc5dfe00e48d9fdd429",
    series: "",
    periodical: "",
    file_extension: "pdf",
    url: "http://bookzz.org/dl/2054864/8e934e",
    convertTo: {
      epub: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F900000%2Fb544a6be89e10bc5dfe00e48d9fdd429&input_format=pdf&output_format=EPUB&download=1",
      fb2: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F900000%2Fb544a6be89e10bc5dfe00e48d9fdd429&input_format=pdf&output_format=FB2&download=1",
      mobi: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F900000%2Fb544a6be89e10bc5dfe00e48d9fdd429&input_format=pdf&output_format=MOBI&download=1",
      txt: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F900000%2Fb544a6be89e10bc5dfe00e48d9fdd429&input_format=pdf&output_format=TXT&download=1",
      rtf: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F900000%2Fb544a6be89e10bc5dfe00e48d9fdd429&input_format=pdf&output_format=RTF&download=1",
    },
    description: "",
    cover:
      "http://libgen.org/covers/900000/b544a6be89e10bc5dfe00e48d9fdd429-d.jpg",
  },
  {
    id: "2379269",
    status: "to be read",
    title: "Instant Web Scraping with Java",
    author: "Ryan Mitchell",
    author_firstname: null,
    author_lastname: "",
    author_middlename: "",
    categories: "Web Development",
    volume: "",
    year: "0",
    edition: null,
    language: "",
    extension: "pdf",
    pages: "0",
    filesize: "1075197",
    md5: "88792de34a41a1f321012853ebb94c51",
    series: "",
    periodical: null,
    file_extension: "pdf",
    url: "http://bookzz.org/dl/2379269/13f821",
    convertTo: {
      epub: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fuserbooks%2F1%2F88792de34a41a1f321012853ebb94c51%2F_as%2F%5BRyan_Mitchell%5D_Instant_Web_Scraping_with_Java%28BookZZ.org%29.pdf&input_format=pdf&output_format=EPUB&download=1",
      fb2: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fuserbooks%2F1%2F88792de34a41a1f321012853ebb94c51%2F_as%2F%5BRyan_Mitchell%5D_Instant_Web_Scraping_with_Java%28BookZZ.org%29.pdf&input_format=pdf&output_format=FB2&download=1",
      mobi: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fuserbooks%2F1%2F88792de34a41a1f321012853ebb94c51%2F_as%2F%5BRyan_Mitchell%5D_Instant_Web_Scraping_with_Java%28BookZZ.org%29.pdf&input_format=pdf&output_format=MOBI&download=1",
      txt: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fuserbooks%2F1%2F88792de34a41a1f321012853ebb94c51%2F_as%2F%5BRyan_Mitchell%5D_Instant_Web_Scraping_with_Java%28BookZZ.org%29.pdf&input_format=pdf&output_format=TXT&download=1",
      rtf: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fuserbooks%2F1%2F88792de34a41a1f321012853ebb94c51%2F_as%2F%5BRyan_Mitchell%5D_Instant_Web_Scraping_with_Java%28BookZZ.org%29.pdf&input_format=pdf&output_format=RTF&download=1",
    },
    description: "",
    cover: null,
  },
  {
    id: "737930",
    status: "to be read",
    title:
      "Beginning Smartphone Web Development: Building Javascript, CSS, HTML and Ajax-Based Applications for iPhone, Android, Palm Pre, Blackberry, Windows Mobile and Nokia S60",
    author: "Gail Frederick, Rajesh Lal",
    author_firstname: null,
    author_lastname: "",
    author_middlename: "",
    categories: "Computers / Programming / Software Development",
    volume: "",
    year: "2010",
    edition: "1st Edition.",
    language: "en",
    extension: "pdf",
    pages: "366",
    filesize: "8375546",
    md5: "5F6BAA45BC35A360CB0C4702FCAF1CF5",
    series: "",
    periodical: "",
    file_extension: "pdf",
    url: "http://bookzz.org/dl/737930/ed8a6e",
    convertTo: null,
    description:
      "This book turned out to have some solid information on figuring out the designing and packaging concepts you need to keep in mind when setting up an appliction for a tiny screen hand held device.   Forget complex rich-media site artwork that makes people linger on a widescreen monitor and think focused task operated by thumbs.   Reminds me of the efficiency principles from the days of 3278's and VT100's in a way ... there's not a lot of room for noise factor on a screen the size of a playing card.   The book emphasizes this and shows a number of good examples.   The section on style guide planning the top, middle and bottom sections of a display page was worth the price of the book.",
    cover:
      "http://libgen.org/covers/311000/5f6baa45bc35a360cb0c4702fcaf1cf5-d.jpg",
  },
  {
    id: "2379675",
    status: "to be read",
    title: "Full Stack Web Development with Backbone.js",
    author: "Patrick Mulder",
    author_firstname: null,
    author_lastname: "",
    author_middlename: "",
    categories: "Development",
    volume: "",
    year: "0",
    edition: null,
    language: "",
    extension: "pdf",
    pages: "0",
    filesize: "6826242",
    md5: "97e1014f6a13249d93081e96dcf2cdaf",
    series: "",
    periodical: null,
    file_extension: "pdf",
    url: "http://bookzz.org/dl/2379675/2cc912",
    convertTo: {
      epub: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fuserbooks%2F2%2F97e1014f6a13249d93081e96dcf2cdaf%2F_as%2F%5BPatrick_Mulder%5D_Full_Stack_Web_Development_with_B%28BookZZ.org%29.pdf&input_format=pdf&output_format=EPUB&download=1",
      fb2: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fuserbooks%2F2%2F97e1014f6a13249d93081e96dcf2cdaf%2F_as%2F%5BPatrick_Mulder%5D_Full_Stack_Web_Development_with_B%28BookZZ.org%29.pdf&input_format=pdf&output_format=FB2&download=1",
      mobi: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fuserbooks%2F2%2F97e1014f6a13249d93081e96dcf2cdaf%2F_as%2F%5BPatrick_Mulder%5D_Full_Stack_Web_Development_with_B%28BookZZ.org%29.pdf&input_format=pdf&output_format=MOBI&download=1",
      txt: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fuserbooks%2F2%2F97e1014f6a13249d93081e96dcf2cdaf%2F_as%2F%5BPatrick_Mulder%5D_Full_Stack_Web_Development_with_B%28BookZZ.org%29.pdf&input_format=pdf&output_format=TXT&download=1",
      rtf: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fuserbooks%2F2%2F97e1014f6a13249d93081e96dcf2cdaf%2F_as%2F%5BPatrick_Mulder%5D_Full_Stack_Web_Development_with_B%28BookZZ.org%29.pdf&input_format=pdf&output_format=RTF&download=1",
    },
    description: "",
    cover: null,
  },
  {
    id: "632635",
    status: "reading",
    title:
      "The Microsoft Expression Web Developer's Guide to ASP.NET 3.5: Learn to create ASP.NET applications using Visual Web Developer 2008",
    author: "Jim Cheshire",
    author_firstname: null,
    author_lastname: "",
    author_middlename: "",
    categories: "Computer science",
    volume: "",
    year: "2007",
    edition: "1",
    language: "en",
    extension: "chm",
    pages: "504",
    filesize: "34203783",
    md5: "053202C3311E1754DDDDD1F5D55F3414",
    series: "",
    periodical: "",
    file_extension: "chm",
    url: "http://bookzz.org/dl/632635/3efe5c",
    convertTo: null,
    description:
      '<P style="MARGIN: 0px">“This book is a great reference for web designers new to ASP.NET who are looking to jump start their development with </P>  <P style="MARGIN: 0px">Visual Web Developer 2008.”</P>  <P style="MARGIN: 0px">Mikhail Arkhipov</P>  <P style="MARGIN: 0px">Principal Development Manager – Web Development Tools</P>  <P style="MARGIN: 0px">Microsoft Corporation</P>  <P style="MARGIN: 0px"> </P>  <P style="MARGIN: 0px">Expression Web introduced ASP.NET to a new group of web developers. This book is designed to help you start using ASP.NET right away to add powerful new features to your website. Don’t worry, you won’t have to learn a lot of programming; instead, you’ll create an ASP.NET application from start to finish using Visual Web Developer 2008, while writing only a very small amount of actual programming code. </P>  <P style="MARGIN: 0px"> </P>  <P style="MARGIN: 0px">DETAILED INFORMATION ON HOW TO…</P>  <P style="MARGIN: 0px">     •    Create and work with websites in Visual Web Developer 2008</P>  <P style="MARGIN: 0px">     •    Use the different compilation and code models in ASP.NET</P>  <P style="MARGIN: 0px">     •    Configure ASP.NET security and other settings</P>  <P style="MARGIN: 0px">     •    Use ASP.NET master pages and user controls</P>  <P style="MARGIN: 0px">     •    Take advantage of ASP.NET membership features for a password-protected website</P>  <P style="MARGIN: 0px">     •    Use form validation in ASP.NET</P>  <P style="MARGIN: 0px">     •    Use CSS, skins, and themes</P>  <P style="MARGIN: 0px">     •    Access, edit, and add data to a database using ASP.NET</P>  <P style="MARGIN: 0px">     •    Send email using ASP.NET</P>  <P style="MARGIN: 0px">     •    Use Ajax and ASP.NET Web services</P>  <P style="MARGIN: 0px">     •    Debug and troubleshoot ASP.NET</P>  <P style="MARGIN: 0px">          . . . and much more!</P>  <P style="MARGIN: 0px"> </P>',
    cover:
      "http://libgen.org/covers/204000/053202c3311e1754ddddd1f5d55f3414-d.jpg",
  },
  {
    id: "682322",
    status: "reading",
    title:
      "Tapestry 5: Building Web Applications: A step-by-step guide to Java Web development with the developer-friendly Apache Tapestry framework",
    author: "Alexander Kolesnikov",
    author_firstname: null,
    author_lastname: "",
    author_middlename: "",
    categories: "Computer science",
    volume: "",
    year: "2008",
    edition: "",
    language: "en",
    extension: "pdf",
    pages: "275",
    filesize: "6891343",
    md5: "77A9A95C504DEDCA6A5D7EC418491432",
    series: "",
    periodical: "",
    file_extension: "pdf",
    url: "http://bookzz.org/dl/682322/4df753",
    convertTo: {
      epub: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F254000%2F77a9a95c504dedca6a5d7ec418491432&input_format=pdf&output_format=EPUB&download=1",
      fb2: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F254000%2F77a9a95c504dedca6a5d7ec418491432&input_format=pdf&output_format=FB2&download=1",
      mobi: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F254000%2F77a9a95c504dedca6a5d7ec418491432&input_format=pdf&output_format=MOBI&download=1",
      txt: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F254000%2F77a9a95c504dedca6a5d7ec418491432&input_format=pdf&output_format=TXT&download=1",
      rtf: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F254000%2F77a9a95c504dedca6a5d7ec418491432&input_format=pdf&output_format=RTF&download=1",
    },
    description:
      'The author Alexander Kolesnikov has significant experience in programming, dating back to 1979 and Fortran. This is his second book that follows the one published in 2007.\rThe book contains elegant introduction to Tapestry 5 with additional focus on building high performing  scalable web apps. The first chapter is introductory, serves as a advert of Tapestry and a taste of things to come. The second helps reader to configure IDE, because practical exercises are encouraged through out the book.\rFrom the next chapter starts the description of the framework. The third illustrates basic Tapestry mechanics that revolve around "Page classes". Author shows how to link them with corresponding views that are enriched html files. Moreover passing data between pages, events and using components is presented. The following chapters provide info on using other parts of the framework like localization, validation etc. and act as a tutorial for building your own components.\rThe book was very easy to read. I can\'t recall anything that would be difficult to comprehend. Boring parts were rare. Global focus on scalability made it fun to read, because it is not a common part of web app tutorials to remind you how session management influences performance.\rOverall the composition of the book is very neat. The most important stuff is put first although you can skip the parts you are familiar with like I did with IDE configuration.\rHoward Levis-Ship the author of Tapestry says that in a good framework "the right thing to do is the easiest one". You can find that idea in every aspect of the framework that is well represented in the book. The focus on scalability is a nice addition to thorough Tapestry 5 description.\rI am not an expert on web apps, so I value the parts that revolve around basics too. Reading the book was fun. Since I did not made any effort into practically using Tapestry during the course of reading it, I was unable tell whether it is better that say JSF with Facelets. However  it provided much insight into web app development with Tapestry. Definitely Tapestry is easier to use, but the real difficulties lie in merging pages with code which I am unable to compare. As usual one needs to try it out in at least medium sized application to find out. Anyway I can recommend this book to anyone who wishes to find out what Tapestry 5 has to offer and anyone who does not feel like an expert in web app development ant would like to go through an introduction on scalable web app development.',
    cover:
      "http://libgen.org/covers/254000/77a9a95c504dedca6a5d7ec418491432-d.jpg",
  },
  {
    id: "739099",
    status: "reading",
    title:
      "Tapestry 5: Building Web Applications: A step-by-step guide to Java Web development with the developer-friendly Apache Tapestry framework",
    author: "Alexander Kolesnikov",
    author_firstname: null,
    author_lastname: "",
    author_middlename: "",
    categories: "",
    volume: "",
    year: "2008",
    edition: "",
    language: "en",
    extension: "pdf",
    pages: "280",
    filesize: "5677349",
    md5: "C8947AA69D6E824CB5DEAA23FEB615F4",
    series: "",
    periodical: "",
    file_extension: "pdf",
    url: "http://bookzz.org/dl/739099/886fc0",
    convertTo: {
      epub: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F313000%2Fc8947aa69d6e824cb5deaa23feb615f4&input_format=pdf&output_format=EPUB&download=1",
      fb2: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F313000%2Fc8947aa69d6e824cb5deaa23feb615f4&input_format=pdf&output_format=FB2&download=1",
      mobi: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F313000%2Fc8947aa69d6e824cb5deaa23feb615f4&input_format=pdf&output_format=MOBI&download=1",
      txt: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F313000%2Fc8947aa69d6e824cb5deaa23feb615f4&input_format=pdf&output_format=TXT&download=1",
      rtf: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F313000%2Fc8947aa69d6e824cb5deaa23feb615f4&input_format=pdf&output_format=RTF&download=1",
    },
    description:
      'The author Alexander Kolesnikov has significant experience in programming, dating back to 1979 and Fortran. This is his second book that follows the one published in 2007.\rThe book contains elegant introduction to Tapestry 5 with additional focus on building high performing  scalable web apps. The first chapter is introductory, serves as a advert of Tapestry and a taste of things to come. The second helps reader to configure IDE, because practical exercises are encouraged through out the book.\rFrom the next chapter starts the description of the framework. The third illustrates basic Tapestry mechanics that revolve around "Page classes". Author shows how to link them with corresponding views that are enriched html files. Moreover passing data between pages, events and using components is presented. The following chapters provide info on using other parts of the framework like localization, validation etc. and act as a tutorial for building your own components.\rThe book was very easy to read. I can\'t recall anything that would be difficult to comprehend. Boring parts were rare. Global focus on scalability made it fun to read, because it is not a common part of web app tutorials to remind you how session management influences performance.\rOverall the composition of the book is very neat. The most important stuff is put first although you can skip the parts you are familiar with like I did with IDE configuration.\rHoward Levis-Ship the author of Tapestry says that in a good framework "the right thing to do is the easiest one". You can find that idea in every aspect of the framework that is well represented in the book. The focus on scalability is a nice addition to thorough Tapestry 5 description.\rI am not an expert on web apps, so I value the parts that revolve around basics too. Reading the book was fun. Since I did not made any effort into practically using Tapestry during the course of reading it, I was unable tell whether it is better that say JSF with Facelets. However  it provided much insight into web app development with Tapestry. Definitely Tapestry is easier to use, but the real difficulties lie in merging pages with code which I am unable to compare. As usual one needs to try it out in at least medium sized application to find out. Anyway I can recommend this book to anyone who wishes to find out what Tapestry 5 has to offer and anyone who does not feel like an expert in web app development ant would like to go through an introduction on scalable web app development.',
    cover:
      "http://libgen.org/covers/313000/c8947aa69d6e824cb5deaa23feb615f4-d.jpg",
  },
  {
    id: "918100",
    status: "reading",
    title:
      "PHP 5 Fast and Easy Web Development (Fast and Easy Web Development)",
    author: "Julie C. Meloni",
    author_firstname: null,
    author_lastname: "",
    author_middlename: "",
    categories: "Компьютеры//Программирование//Языки программирования",
    volume: "",
    year: "2008",
    edition: "1",
    language: "en",
    extension: "pdf",
    pages: "568",
    filesize: "11374853",
    md5: "be897bd1bfd4dab38767db24da2a794b",
    series: "",
    periodical: "",
    file_extension: "pdf",
    url: "http://bookzz.org/dl/918100/92d14e",
    convertTo: null,
    description:
      "Don't spend your time wading through manuals to learn PHP 5. Spend it doing what you do best - creating web pages! With \"PHP 5 Fast & Easy Web Development\" you can get up and running with PHP 5, Apache, and MySQL with ease. By the time you're finished, you'll be able to display dynamic content, build your own contact management system, create custom reports, work with XML, and much more. Less time, less effort, more results!",
    cover:
      "http://libgen.org/covers/493000/be897bd1bfd4dab38767db24da2a794b-d.jpg",
  },
  {
    id: "932675",
    status: "reading",
    title:
      "Macromedia Flash MX 2004 Fast & Easy Web Development (Fast & Easy Web Development)",
    author: "Lisa A. Bucki",
    author_firstname: null,
    author_lastname: "",
    author_middlename: "",
    categories: "Компьютеры//Программы//Продукты Macromedia",
    volume: "",
    year: "2006",
    edition: "1",
    language: "en",
    extension: "chm",
    pages: "368",
    filesize: "20283817",
    md5: "ac3818a5c99cee02d2e9f91b9ce5e693",
    series: "",
    periodical: "",
    file_extension: "chm",
    url: "http://bookzz.org/dl/932675/279226",
    convertTo: null,
    description:
      "What better way for readers to learn the newest version of Flash than with the Fast & Easy series!  Macromedia Flash MX 2004 Fast & Easy Web Development presents solution-oriented techniques for creating dynamic animations and graphics for the Web.  Through illustrated step-by step instructions, this title demonstrates the technologies of Macromedia Flash 2004 while providing practical applications as well.   Covering both the Windows and Mac versions, readers will learn important Flash skills such as using symbols and tweening, using vector-based content for faster downloads, and optimizing animations for the Web.  Using a hands-on approach to yield fast results and downloadable sample files to practice techniques, this book is suitable for both beginners and current users aspiring to learn the newest features of Flash.",
    cover:
      "http://libgen.org/covers/508000/ac3818a5c99cee02d2e9f91b9ce5e693-d.jpg",
  },
  {
    id: "1065073",
    status: "reading",
    title:
      "PHP Fast & Easy Web Development, 2nd Edition (Fast & Easy Web Development)",
    author: "Julie C. Meloni",
    author_firstname: null,
    author_lastname: "",
    author_middlename: "",
    categories: "",
    volume: "",
    year: "2002",
    edition: "2",
    language: "en",
    extension: "epub",
    pages: "0",
    filesize: "4308292",
    md5: "D6BB2B23B44DE18BE1344ED659044D7F",
    series: "",
    periodical: "",
    file_extension: "epub",
    url: "http://bookzz.org/dl/1065073/8e89d0",
    convertTo: {
      fb2: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F625000%2Fd6bb2b23b44de18be1344ed659044d7f&input_format=epub&output_format=FB2&download=1",
      pdf: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F625000%2Fd6bb2b23b44de18be1344ed659044d7f&input_format=epub&output_format=PDF&download=1",
      mobi: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F625000%2Fd6bb2b23b44de18be1344ed659044d7f&input_format=epub&output_format=MOBI&download=1",
      txt: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F625000%2Fd6bb2b23b44de18be1344ed659044d7f&input_format=epub&output_format=TXT&download=1",
      rtf: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F625000%2Fd6bb2b23b44de18be1344ed659044d7f&input_format=epub&output_format=RTF&download=1",
    },
    description: "",
    cover:
      "http://libgen.org/covers/625000/d6bb2b23b44de18be1344ed659044d7f-d.jpg",
  },
  {
    id: "1065771",
    status: "reading",
    title: "Perl Fast & Easy Web Development (Fast & Easy Web Development)",
    author: "Leslie W. Bate",
    author_firstname: null,
    author_lastname: "",
    author_middlename: "",
    categories: "",
    volume: "",
    year: "2002",
    edition: "1",
    language: "en",
    extension: "epub",
    pages: "0",
    filesize: "19712611",
    md5: "854BBDC8D5895E7E5DE6A260D9CA1745",
    series: "",
    periodical: "",
    file_extension: "epub",
    url: "http://bookzz.org/dl/1065771/79a03a",
    convertTo: null,
    description: "",
    cover:
      "http://libgen.org/covers/626000/854bbdc8d5895e7e5de6a260d9ca1745-d.jpg",
  },
  {
    id: "2052811",
    status: "reading",
    title:
      "PHP Oracle web development : data processing, security, caching, XML, web services and AJAX : a practical guide to combining the power, performance, scalability, and reliability of Oracle Database with the ease of use, short development time, and high per",
    author: "Yuli Vasiliev",
    author_firstname: null,
    author_lastname: "",
    author_middlename: "",
    categories: "Computers\\\\Programming: Programming Languages",
    volume: "",
    year: "2007",
    edition: "",
    language: "en",
    extension: "pdf",
    pages: "378",
    filesize: "2854143",
    md5: "1402dce1dbcbf160ad63472ca6bc5de0",
    series: "",
    periodical: "",
    file_extension: "pdf",
    url: "http://bookzz.org/dl/2052811/ac231e",
    convertTo: {
      epub: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F898000%2F1402dce1dbcbf160ad63472ca6bc5de0&input_format=pdf&output_format=EPUB&download=1",
      fb2: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F898000%2F1402dce1dbcbf160ad63472ca6bc5de0&input_format=pdf&output_format=FB2&download=1",
      mobi: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F898000%2F1402dce1dbcbf160ad63472ca6bc5de0&input_format=pdf&output_format=MOBI&download=1",
      txt: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F898000%2F1402dce1dbcbf160ad63472ca6bc5de0&input_format=pdf&output_format=TXT&download=1",
      rtf: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F898000%2F1402dce1dbcbf160ad63472ca6bc5de0&input_format=pdf&output_format=RTF&download=1",
    },
    description: "",
    cover:
      "http://libgen.org/covers/898000/1402dce1dbcbf160ad63472ca6bc5de0-g.jpg",
  },
  {
    id: "2082314",
    status: "reading",
    title:
      "PHP Oracle Web Development: Data processing, Security, Caching, XML, Web Services, and Ajax: A practical guide to combining the power, performance, ... development time, and high performance of PHP",
    author: "Yuli Vasiliev",
    author_firstname: null,
    author_lastname: "",
    author_middlename: "",
    categories: "Computers\\\\Programming",
    volume: "",
    year: "2007",
    edition: "1st Ed.",
    language: "en",
    extension: "pdf",
    pages: "392",
    filesize: "7448117",
    md5: "07acfe7cfe5752b032a8ea8739441048",
    series: "",
    periodical: "",
    file_extension: "pdf",
    url: "http://bookzz.org/dl/2082314/6eb60e",
    convertTo: null,
    description: "",
    cover:
      "http://libgen.org/covers/928000/07acfe7cfe5752b032a8ea8739441048-d.jpg",
  },
  {
    id: "2171074",
    status: "read",
    title: ".NET Mobile Web Developers Guide. Web Developer's Guide",
    author:
      "Steve Milroy, Ken Cox, Doug Safford, Laura Barker, Amit Kalani and Wei Meng Lee (Auth.)",
    author_firstname: null,
    author_lastname: "",
    author_middlename: "",
    categories: "",
    volume: "",
    year: "2001",
    edition: "",
    language: "en",
    extension: "pdf",
    pages: "415",
    filesize: "11034156",
    md5: "80e1a0cd6adabf64d9f4a2bfaaa5e4da",
    series: "",
    periodical: "",
    file_extension: "pdf",
    url: "http://bookzz.org/dl/2171074/8e4b6b",
    convertTo: null,
    description: "",
    cover:
      "http://ars.els-cdn.com/content/image/3-s2.0-B9781928994565X50002-cov150h.gif",
  },
  {
    id: "2216623",
    status: "read",
    title:
      "Tapestry 5: Building Web Applications: A step-by-step guide to Java Web development with the developer-friendly Apache Tapestry framework",
    author: "Alexander Kolesnikov",
    author_firstname: null,
    author_lastname: "",
    author_middlename: "",
    categories: "",
    volume: "",
    year: "2008",
    edition: "",
    language: "en",
    extension: "pdf",
    pages: "280",
    filesize: "6793503",
    md5: "b97b7bdc33123ccc81a689f7a0b079dd",
    series: "",
    periodical: "",
    file_extension: "pdf",
    url: "http://bookzz.org/dl/2216623/62f467",
    convertTo: {
      epub: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F1047000%2Fb97b7bdc33123ccc81a689f7a0b079dd&input_format=pdf&output_format=EPUB&download=1",
      fb2: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F1047000%2Fb97b7bdc33123ccc81a689f7a0b079dd&input_format=pdf&output_format=FB2&download=1",
      mobi: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F1047000%2Fb97b7bdc33123ccc81a689f7a0b079dd&input_format=pdf&output_format=MOBI&download=1",
      txt: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F1047000%2Fb97b7bdc33123ccc81a689f7a0b079dd&input_format=pdf&output_format=TXT&download=1",
      rtf: "http://bookzz.org/cs2/liveconverter/?source=http%3A%2F%2Fdlx.bookzz.org%2Fgenesis%2F1047000%2Fb97b7bdc33123ccc81a689f7a0b079dd&input_format=pdf&output_format=RTF&download=1",
    },
    description: "",
    cover:
      "http://libgen.org/covers/1047000/b97b7bdc33123ccc81a689f7a0b079dd-d.jpg",
  },
  {
    id: "2329493",
    status: "read",
    title: "Learn Java for Web Development: Modern Java Web Development",
    author: "Vishal Layka",
    author_firstname: null,
    author_lastname: "",
    author_middlename: "",
    categories: "",
    volume: "",
    year: "2014",
    edition: "1",
    language: "en",
    extension: "pdf",
    pages: "472",
    filesize: "17702229",
    md5: "2399df2930020fa747e0c8d17bfc8720",
    series: "",
    periodical: "",
    file_extension: "pdf",
    url: "http://bookzz.org/dl/2329493/792d5a",
    convertTo: null,
    description: "",
    cover:
      "http://libgen.org/covers/1160000/2399df2930020fa747e0c8d17bfc8720-d.jpg",
  },
];
